### ISSUE TITLE
Continuous Blocking and Manual Twitter Handle Import List

### ISSUE THREAD

**Issue by aliafshany** [bxljoy/twitter-blocking-assistant#1]
Thanks for this amazing code. Here is the issue: the code works, but after a while (maybe 100 blocks), it stops and you have to rerun it to continue blocking. However, it starts from the beginning each time. Are there any options to allow it to continue blocking the rest without restarting? Alternatively, can we manually import a list of Twitter handles?

**Comment by bxljoy** [comment]
> Thanks for this amazing code. Here is the issue: the code works, but after a while (maybe 100 blocks), it stops and you have to rerun it to continue blocking. However, it starts from the beginning each time. Are there any options to allow it to continue blocking the rest without restarting? Alternatively, can we manually import a list of Twitter handles?

Yes, you're right. The issue exsits as you said. Actually, I tried to fix it but failed. In my opinion, Twitter uses the lazy loading to show the users list and I can't get all the users information in the first place. In the previous version, I tried to scroll down the page to render more users and using a for loop to restart the exexcution. But it didn't work, I still cannot get the rest of users information. 

About the list of Twitter handles, I can't understand this idea, could you give me more details about it? Or you can implement 
 it by yourself and create a PR, then we can discuss more. Thank you.

**Comment by bxljoy** [comment]
I have fixed the problem of blocking those blocked users.
